export const KEY='infinite-realms-v2';
export const LOCATIONS=[{id:'camp',name:'اردوگاه سپیده',x:21,y:70,description:'آتش کوچکی در سایه کوهستان روشن است.',links:['forest']},{id:'forest',name:'جنگل نجوا',x:45,y:52,description:'درختان کهن و ردپاهای ناشناخته.',links:['camp','ruins']},{id:'ruins',name:'ویرانه‌های مه',x:72,y:30,description:'برج سنگی فراموش‌شده در مه پنهان است.',links:['forest']}];
export const CLASSES={warrior:{label:'جنگجو',hp:14,abilities:['ضربه سنگین','سپر دفاعی'],items:[{id:'potion',name:'معجون درمان',quantity:2,heal:5},{id:'sword',name:'شمشیر آهنی',quantity:1}]},mage:{label:'جادوگر',hp:9,abilities:['جرقه جادویی','سپر جادویی'],items:[{id:'potion',name:'معجون درمان',quantity:2,heal:5},{id:'staff',name:'عصای چوبی',quantity:1}]},ranger:{label:'تکاور',hp:11,abilities:['تیر دقیق','ردیابی'],items:[{id:'potion',name:'معجون درمان',quantity:2,heal:5},{id:'bow',name:'کمان شکار',quantity:1}]}};
export function newState(){return {schema:1,activeCampaign:null,campaigns:[]}};
export function createCampaign(state,name,heroName,heroClass='warrior'){if(!name?.trim()||!heroName?.trim()||!CLASSES[heroClass])throw Error('نام کمپین، قهرمان و کلاس معتبر لازم است');const template=CLASSES[heroClass];const id=globalThis.crypto?.randomUUID?.()||String(Date.now()+Math.random());const campaign={id,name:name.trim().slice(0,60),hero:{name:heroName.trim().slice(0,40),class:heroClass,hp:template.hp,maxHp:template.hp,level:1,abilities:[...template.abilities],inventory:template.items.map(x=>({...x}))},location:'camp',discovered:['camp'],history:[{kind:'story',text:'چشمانت را در اردوگاه سپیده باز می‌کنی. جنگل نجوا در دوردست دیده می‌شود.'}],turn:0};return {...state,activeCampaign:id,campaigns:[...state.campaigns,campaign]}}
export const active=s=>s.campaigns.find(c=>c.id===s.activeCampaign)||null;
export function updateCampaign(s,id,fn){return {...s,campaigns:s.campaigns.map(c=>c.id===id?fn(c):c)}};
export function travel(s,to){const c=active(s);if(!c)throw Error('ابتدا کمپین انتخاب کن');const here=LOCATIONS.find(p=>p.id===c.location);const dest=LOCATIONS.find(p=>p.id===to);if(!dest||!here.links.includes(to))throw Error('از این مکان مسیر مستقیمی وجود ندارد');return updateCampaign(s,c.id,x=>({...x,location:to,discovered:[...new Set([...x.discovered,to])],turn:x.turn+1,history:[...x.history,{kind:'travel',text:`به ${dest.name} رسیدی. ${dest.description}`}]}))}
export function useItem(s,id){const c=active(s);if(!c)throw Error('قهرمان انتخاب نشده');const item=c.hero.inventory.find(i=>i.id===id&&i.quantity>0);if(!item)throw Error('این وسیله در کوله‌پشتی نیست');if(!item.heal)throw Error('این وسیله مصرف‌شدنی نیست');if(c.hero.hp>=c.hero.maxHp)throw Error('جان قهرمان کامل است');return updateCampaign(s,c.id,x=>({...x,hero:{...x.hero,hp:Math.min(x.hero.maxHp,x.hero.hp+item.heal),inventory:x.hero.inventory.map(i=>i.id===id?{...i,quantity:i.quantity-1}:i)},history:[...x.history,{kind:'item',text:`${item.name} استفاده شد؛ جان بازیابی شد.`}]}))}
export function choose(s,text){const c=active(s);if(!c)throw Error('ابتدا کمپین انتخاب کن');const action=String(text||'').trim().slice(0,350);if(!action)throw Error('اقدام را بنویس');return updateCampaign(s,c.id,x=>({...x,turn:x.turn+1,history:[...x.history,{kind:'action',text:action},{kind:'story',text:'اقدامت ثبت شد. در نسخه پایه، راوی هوشمند هنوز متصل نیست؛ برای حرکت از نقشه استفاده کن.'}]}))}
export function load(storage){try{const v=JSON.parse(storage.getItem(KEY));if(v?.schema===1&&Array.isArray(v.campaigns))return v}catch{}return newState()}
export function save(storage,s){storage.setItem(KEY,JSON.stringify(s))}
